"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { useAppState } from "@/hooks/use-app-state";

const ADMIN_NAVIGATION = [
  { href: "/admin/dashboard", label: "Dashboard" },
  { href: "/admin/audit-logs", label: "Audit Logs" },
];

/**
 * Displays mock audit entries generated by task and auth interactions.
 */
export default function AdminAuditLogsPage() {
  const router = useRouter();
  const { authReady, currentUser, auditLogs } = useAppState();

  useEffect(() => {
    if (!authReady) {
      return;
    }

    if (!currentUser) {
      router.replace("/login");
      return;
    }

    if (currentUser.role !== "admin") {
      router.replace("/user/dashboard");
    }
  }, [authReady, currentUser, router]);

  if (!authReady || !currentUser || currentUser.role !== "admin") {
    return null;
  }

  return (
    <AppShell
      sidebarTitle="Admin Dashboard"
      heading="Audit Log"
      navigation={ADMIN_NAVIGATION}
    >
      <section className="section-block">
        <div className="table-card">
          <table>
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>User</th>
                <th>Action</th>
                <th>Details</th>
              </tr>
            </thead>
            <tbody>
              {auditLogs.map((entry) => (
                <tr key={entry.id}>
                  <td>{entry.timestamp}</td>
                  <td>{entry.userName}</td>
                  <td>{entry.action}</td>
                  <td>{entry.details}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </AppShell>
  );
}
